CREATE TABLE IF NOT EXISTS ARMORY
(
    ID         BIGINT UNSIGNED AUTO_INCREMENT,
    WEAPON     TEXT          NOT NULL,
    COUNT      INT DEFAULT 0 NOT NULL,
    ARMORY_JOB TEXT          NOT NULL,
    CONSTRAINT ID
        UNIQUE (ID)
);

ALTER TABLE ARMORY
    ADD PRIMARY KEY (ID);

