RegisterNetEvent('disc-hacker:notifyRadius')
AddEventHandler('disc-hacker:notifyRadius', function(coords, radius, time)
    exports['mythic_notify']:SendAlert('error', "Hack in progress, updating approximate location")
    print(coords.x .. ' ' .. coords.y .. ' ' .. coords.z)
    local blip = AddBlipForRadius(coords.x, coords.y, coords.z, radius)
    SetBlipHighDetail(blip, true)
    SetBlipColour(blip, 1)
    SetBlipAlpha(blip, 250)
    SetBlipAsShortRange(blip, true)
    Citizen.Wait(time)
    RemoveBlip(blip)
end)