CREATE TABLE IF NOT EXISTS JOB_CARS
(
    ID     BIGINT UNSIGNED AUTO_INCREMENT,
    OWNER  TEXT                 NOT NULL,
    PLATE  TEXT                 NOT NULL,
    PROPS  LONGTEXT             NULL,
    `STORED` BOOLEAN DEFAULT TRUE NULL,
    CONSTRAINT ID
        UNIQUE (ID)
);

ALTER TABLE JOB_CARS
    ADD PRIMARY KEY (ID);

